import sqlalchemy as sa
from alembic import op

revision = "8bfbd45359dd"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade():
  # SQLiteでは主キーの削除ができないため、テーブル再作成で対応
  # local_products
  op.rename_table("local_products", "local_products_old")
  op.create_table(
    "local_products",
    sa.Column("product_id", sa.String(length=13), primary_key=True, nullable=False),
    sa.Column("product_name", sa.String(length=100), nullable=False),
    sa.Column("price", sa.Integer(), nullable=False),
    sa.Column("store_id", sa.String(length=50), nullable=False, default="default_store"),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
  )
  # データ移行（必要ならSQLで）
  op.execute(
    "INSERT INTO local_products (product_id, product_name, price, store_id, created_at, updated_at) SELECT product_code, name, price, store_id, created_at, updated_at FROM local_products_old;"
  )
  op.drop_table("local_products_old")

  # products
  op.rename_table("products", "products_old")
  op.create_table(
    "products",
    sa.Column("product_id", sa.String(length=13), primary_key=True, nullable=False),
    sa.Column("product_name", sa.String(length=100), nullable=False),
    sa.Column("price", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
  )
  op.execute(
    "INSERT INTO products (product_id, product_name, price, created_at, updated_at) SELECT product_code, name, price, created_at, updated_at FROM products_old;"
  )
  op.drop_table("products_old")

  # インデックス再作成（必要なら）
  op.create_index(op.f("ix_local_products_product_id"), "local_products", ["product_id"], unique=False)
  op.create_index(op.f("ix_products_product_id"), "products", ["product_id"], unique=False)
  op.create_index(op.f("ix_transaction_details_id"), "transaction_details", ["id"], unique=False)
  op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
  op.drop_index(op.f("ix_transaction_details_id"), table_name="transaction_details")
  op.add_column("products", sa.Column("name", sa.VARCHAR(length=100), nullable=False))
  op.add_column("products", sa.Column("product_code", sa.VARCHAR(length=50), nullable=False))
  op.add_column("products", sa.Column("id", sa.INTEGER(), nullable=False))
  op.drop_index(op.f("ix_products_product_id"), table_name="products")
  op.create_index(op.f("ix_products_product_code"), "products", ["product_code"], unique=1)
  op.drop_column("products", "product_name")
  op.drop_column("products", "product_id")
  op.add_column("local_products", sa.Column("name", sa.VARCHAR(length=100), nullable=False))
  op.add_column("local_products", sa.Column("product_code", sa.VARCHAR(length=50), nullable=False))
  op.add_column("local_products", sa.Column("id", sa.INTEGER(), nullable=False))
  op.drop_index(op.f("ix_local_products_product_id"), table_name="local_products")
  op.create_index(op.f("ix_local_products_product_code"), "local_products", ["product_code"], unique=1)
  op.drop_column("local_products", "product_name")
  op.drop_column("local_products", "product_id")
  # ### end Alembic commands ###
